-- Solutions

-- EASY
-- 1. Find all delivered orders with customer names.


-- 2. Show every customer, including customers who have never placed an order.

-- 3. Find the total revenue generated by each product category.


-- MEDIUM
-- 1. Find customers who have never placed an order.

-- 2. For each product category, find the lowest-priced product that has generated at least one delivered order.

-- 3. Find the top 3 customers by delivered revenue.

-- 4. Find cities where total delivered revenue exceeds $1,000.

-- 5. Find products that have never been ordered.


/* 
Bonus Challenge
Return:
Customer name
City
Number of delivered orders
Total delivered spending
Average order value

Include only customers whose delivered spending is greater than the average delivered spending of all customers.
Sort the results by total spending in descending order.
*/
