CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(50),
    city VARCHAR(50)
);


INSERT INTO customers
(customer_id, customer_name, city)
VALUES
(101, 'Michael Johnson', 'New York'),
(102, 'Sophia Martinez', 'Chicago'),
(103, 'Daniel Kim', 'Boston'),
(104, 'Priya Sharma', 'Seattle'),
(105, 'James Wilson', 'Boston'),
(106, 'Olivia Brown', 'Seattle'),
(107, 'Emma Davis', 'Denver');


-- Create Orders Table


CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    order_date DATE,
    quantity INT,
    total_amount DECIMAL(10,2),
    order_status VARCHAR(20)
);



-- Insert Orders Data


INSERT INTO orders
(order_id, customer_id, product_id, order_date, quantity, total_amount, order_status)
VALUES

-- Delivered orders
(1001, 101, 201, '2026-01-03', 1, 1200.00, 'Delivered'),

(1002, 102, 202, '2026-01-05', 4, 320.00, 'Delivered'),

(1003, 101, 203, '2026-01-10', 2, 50.00, 'Delivered'),

(1004, 103, 204, '2026-01-12', 10, 50.00, 'Delivered'),

(1005, 104, 205, '2026-01-15', 2, 600.00, 'Delivered'),

(1006, 102, 206, '2026-01-18', 1, 250.00, 'Cancelled'),

(1007, 105, 207, '2026-01-20', 3, 135.00, 'Delivered'),

(1008, 103, 202, '2026-01-22', 2, 160.00, 'Delivered'),

(1009, 101, 209, '2026-01-24', 5, 60.00, 'Pending'),

(1010, 106, 201, '2026-01-26', 1, 1300.00, 'Delivered'),

(1011, 104, 206, '2026-01-27', 2, 500.00, 'Delivered');


-- Create Products Table


CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(50),
    category VARCHAR(50),
    price DECIMAL(10,2)
);


-- Insert Product Data

INSERT INTO products
(product_id, product_name, category, price)
VALUES

(201, 'Laptop', 'Electronics', 1200.00),

(202, 'Chair', 'Furniture', 80.00),

(203, 'Mouse', 'Electronics', 25.00),

(204, 'Notebook', 'Office Supplies', 5.00),

(205, 'Monitor', 'Electronics', 300.00),

(206, 'Desk', 'Furniture', 250.00),

(207, 'Keyboard', 'Electronics', 45.00),

(208, 'Headphones', 'Electronics', 120.00),

(209, 'Printer Paper', 'Office Supplies', 12.00),

(210, 'Tablet', 'Electronics', 500.00);


-- EASY
-- 1. Find all delivered orders with customer names.

-- 2. Show every customer, including customers who have never placed an order.

-- 3. Find the total revenue generated by each product category.


-- MEDIUM
-- 1. Find customers who have never placed an order.

-- 2. For each product category, find the lowest-priced product that has generated at least one delivered order.

-- 3. Find the top 3 customers by delivered revenue.

-- 4. Find cities where total delivered revenue exceeds $1,000.

-- 5. Find products that have never been ordered.


/* 
Bonus Challenge
Return:
Customer name
City
Number of delivered orders
Total delivered spending
Average order value

Include only customers whose delivered spending is greater than the average delivered spending of all customers.
Sort the results by total spending in descending order.
*/
