-- Solutions

-- EASY
-- 1. Find all delivered orders with customer names.
SELECT
    o.order_id,
    c.customer_name,
    o.order_status
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.order_status = 'Delivered';

-- 2. Show every customer, including customers who have never placed an order.
SELECT
    c.customer_id,
    c.customer_name,
    o.order_id
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id;

-- 3. Find the total revenue generated by each product category.
SELECT
    p.category,
    SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.category;

-- MEDIUM
-- 1. Find customers who have never placed an order.

SELECT
    c.customer_id,
    c.customer_name
FROM customers c
WHERE NOT EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
);

-- 2. Find the top 3 customers by delivered revenue.
SELECT
    c.customer_name,
    SUM(p.price * o.quantity) AS delivered_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN products p
    ON o.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_name
ORDER BY delivered_revenue DESC
LIMIT 3;

-- 3. Find cities where total delivered revenue exceeds $1,000.
SELECT
    c.city,
    SUM(p.price * o.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN products p
    ON o.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY c.city
HAVING SUM(p.price * o.quantity) > 1000;




/* 
Bonus Challenge
Return:
Customer name
City
Number of delivered orders
Total delivered spending
Average order value

Include only customers whose delivered spending is greater than the average delivered spending of all customers.
Sort the results by total spending in descending order.
*/
WITH delivered AS (
    SELECT
        o.customer_id,
        COUNT(*) AS delivered_order_count,
        SUM(o.total_amount) AS total_delivered_spending,
        AVG(o.total_amount) AS avg_order_value
    FROM orders o
    WHERE o.order_status = 'Delivered'
    GROUP BY o.customer_id
),
overall_avg AS (
    SELECT AVG(total_delivered_spending) AS avg_delivered_spending
    FROM delivered
)
SELECT
    c.customer_name,
    c.city,
    d.delivered_order_count,
    d.total_delivered_spending,
    d.avg_order_value
FROM delivered d
JOIN customers c ON c.customer_id = d.customer_id
CROSS JOIN overall_avg oa
WHERE d.total_delivered_spending > oa.avg_delivered_spending
ORDER BY d.total_delivered_spending DESC;
