-- Solutions

-- EASY
-- 1. Find all delivered orders with customer names.
SELECT
    o.order_id,
    c.customer_name,
    o.order_status
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.order_status = 'Delivered';

-- 2. Show every customer, including customers who have never placed an order.
SELECT
    c.customer_id,
    c.customer_name,
    o.order_id
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id;

-- 3. Find the total revenue generated by each product category.
SELECT
    p.category,
    SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
    ON o.product_id = p.product_id
WHERE o.order_status = 'Delivered'
GROUP BY p.category;

-- MEDIUM
-- 1. Find customers who have never placed an order.

SELECT
    c.customer_id,
    c.customer_name
FROM customers c
WHERE NOT EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
);

-- 2. For each product category, find the lowest-priced product that has generated at least one delivered order.

-- 3. Find the top 3 customers by delivered revenue.

-- 4. Find cities where total delivered revenue exceeds $1,000.

-- 5. Find products that have never been ordered.


/* 
Bonus Challenge
Return:
Customer name
City
Number of delivered orders
Total delivered spending
Average order value

Include only customers whose delivered spending is greater than the average delivered spending of all customers.
Sort the results by total spending in descending order.
*/
